name: 'File Sync'
description: 'A GitHub Action for syncing files from a different repository'
inputs:
  token:
    description: 'GitHub access token'
    required: true
  files:
    default: '{}'
    description: 'JSON string containing the file mapping'
runs:
  using: 'node12'
  main: 'dist/index.js'
